// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package modals

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateUserModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal fade\" id=\"create_user_modal\" tabindex=\"-1\" aria-hidden=\"true\"><div class=\"modal-dialog modal-dialog-centered modal-lg\"><div class=\"modal-content\"><div class=\"modal-header bg-light p-3\"><h5 class=\"modal-title\">Thêm người dùng</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div><form id=\"form_create_user\"><div class=\"modal-body\"><div class=\"row g-3\"><div class=\"col-lg-6\"><label class=\"form-label\">Họ <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" name=\"last_name\" placeholder=\"Nhập họ của bạn\" required></div><div class=\"col-lg-6\"><label class=\"form-label\">Tên <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" name=\"first_name\" placeholder=\"Nhập tên của bạn\" reqired></div><div class=\"col-lg-6\"><label class=\"form-label\">Email <span class=\"text-danger\">*</span></label> <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Nhập email\" required></div><div class=\"col-lg-6\"><label class=\"form-label\">Trạng thái <span class=\"text-danger\">*</span></label><div class=\"d-flex gap-3 mt-1\"><div class=\"form-check\"><input class=\"form-check-input\" type=\"radio\" name=\"status\" id=\"status1\" value=\"1\" checked> <label class=\"form-check-label\" for=\"status1\">Hiện</label></div><div class=\"form-check\"><input class=\"form-check-input\" type=\"radio\" name=\"status\" id=\"status0\" value=\"2\"> <label class=\"form-check-label\" for=\"status0\">Ẩn</label></div></div></div></div></div><div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-light\" data-bs-dismiss=\"modal\">Đóng</button> <button type=\"submit\" class=\"btn btn-success\" id=\"btn-submit-create\">Xác nhận</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
