// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package modals

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DeleteUserModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"modal fade\" id=\"delete_modal\" tabindex=\"-1\" aria-hidden=\"true\"><div class=\"modal-dialog modal-dialog-centered\"><div class=\"modal-content\"><div class=\"modal-header bg-danger p-3\"><h5 class=\"modal-title text-white\">Xóa người dùng</h5><button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div><form id=\"form_delete_user\"><div class=\"modal-body text-center p-4\"><i class=\"ri-delete-bin-fill display-4 text-danger mb-3\"></i><h5 class=\"mb-3\">Xác nhận xóa</h5><p class=\"text-muted mb-0\">Bạn có muốn xóa vĩnh viễn người dùng này không? Hành động này không thể hoàn tác.</p><input type=\"hidden\" name=\"id\" id=\"delete_user_id\"></div><div class=\"modal-footer justify-content-center\"><button type=\"button\" class=\"btn btn-light\" data-bs-dismiss=\"modal\">Hủy bỏ</button> <button type=\"submit\" class=\"btn btn-danger\" id=\"btn-submit-delete\">Vâng, xóa đi!</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
