// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "app/modules/admins/users/entity"

func UpdateUserTempl(user *entity.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row\"><div class=\"col-xl-3 col-lg-4\"><div class=\"card mb-4\"><div class=\"card-body text-center\"><div class=\"mb-3\"><img src=\"/static/images/users/user-dummy-img.jpg\" class=\"rounded-circle avatar-lg img-thumbnail\" alt=\"User Image\" style=\"width: 120px; height: 120px; object-fit: cover;\"></div><h5 class=\"mb-1\" id=\"display_full_name\">User Name</h5></div></div><div class=\"card mb-4\"><div class=\"card-body\"><div class=\"mb-2\"><i class=\"bx bx-user me-2\"></i> Created by : Super Admin</div><div class=\"mb-2\"><i class=\"bx bx-calendar me-2\"></i> Created : 2026-05-14 14:54</div><div class=\"mb-2\"><i class=\"bx bx-calendar-check me-2\"></i> Updated : 2026-05-14 14:54</div></div></div></div><div class=\"col-xl-9 col-lg-8\"><div class=\"card\"><div class=\"card-header\"><ul class=\"nav nav-tabs card-header-tabs\" role=\"tablist\"><li class=\"nav-item\"><a class=\"nav-link active\" data-bs-toggle=\"tab\" href=\"#personalDetails\" role=\"tab\">Personal Details</a></li></ul></div><div class=\"card-body\"><div class=\"tab-content\"><div class=\"tab-pane active\" id=\"personalDetails\" role=\"tabpanel\"><form id=\"form_update_user\"><div class=\"row g-3\"><div class=\"col-lg-6\"><label class=\"form-label\">Last name <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" name=\"last_name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(user.LastName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admins/users/components/update_user_form.templ`, Line: 40, Col: 88}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" placeholder=\"Nhập họ\" required></div><div class=\"col-lg-6\"><label class=\"form-label\">First name <span class=\"text-danger\">*</span></label> <input type=\"text\" class=\"form-control\" name=\"first_name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(user.FirstName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admins/users/components/update_user_form.templ`, Line: 44, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" placeholder=\"Nhập tên\" required></div><div class=\"col-lg-6\"><label class=\"form-label\">Email <span class=\"text-danger\">*</span></label> <input type=\"email\" class=\"form-control\" name=\"email\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(user.Email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admins/users/components/update_user_form.templ`, Line: 48, Col: 82}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" placeholder=\"Nhập email\" required></div><div class=\"col-lg-6\"><label class=\"form-label\">Status <span class=\"text-danger\">*</span></label><div class=\"d-flex gap-3 mt-1\"><div class=\"form-check\"><input class=\"form-check-input\" type=\"radio\" name=\"status\" id=\"statusActive\" value=\"1\" checked> <label class=\"form-check-label\" for=\"statusActive\">Active</label></div><div class=\"form-check\"><input class=\"form-check-input\" type=\"radio\" name=\"status\" id=\"statusInactive\" value=\"2\"> <label class=\"form-check-label\" for=\"statusInactive\">Inactive</label></div></div></div><input id=\"user_id\" type=\"hidden\" class=\"form-control\" name=\"id\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(user.ID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admins/users/components/update_user_form.templ`, Line: 63, Col: 89}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><div class=\"col-12 text-end mt-4\"><button type=\"button\" class=\"btn btn-light me-2\">Cancel</button> <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-submit-update\">Update</button></div></div></form></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
